project_id = "ujwsbmjnpvzfvcjorlxl"

[functions.wolf-chat]
verify_jwt = false

[functions.mercadopago-create-preference]
verify_jwt = false

[functions.mercadopago-webhook]
verify_jwt = false

[functions.vinted-scraper]
verify_jwt = false

[functions.login-check]
verify_jwt = false
